version: '2'
services:
  web:
    image: web
    build:
      context: .
      dockerfile: provision/apache/Dockerfile
    environment:
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=swordfish
      - DB_HOST=database
      - WP_HOME=http://localhost:5050/
      - WP_DEBUG=0
      - WP_SITEURL=http://localhost:5050/cms
    ports:
      - 5050:80
    volumes:
      - .:/var/www/html
      - ./docker/apache/certs/:/etc/apache2/ssl/
      - ./provision/apache/sites-available:/etc/apache2/sites-available
