version: '2'
services:
  web:
    image: web
    links:
      - database:mysql
    build:
      context: .
      dockerfile: provision/apache/Dockerfile
    environment:
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASSWORD=swordfish
      - DB_HOST=database
      - WP_HOME=http://localhost:5050/
      - WP_DEBUG=0
      - WP_SITEURL=http://localhost:5050/cms
    ports:
      - 5050:80
    volumes:
      - .:/var/www/html
      - ./provision/apache/sites-available:/etc/apache2/sites-available
  database:
    image: mysql
    environment:
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=swordfish
      - MYSQL_ROOT_PASSWORD=swordfish
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./provision/mysql/data:/var/lib/mysql
